spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: false
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3333/eureka

